# Generated by Django 2.1.5 on 2019-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190128_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='tytuł', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='tekst postu'),
        ),
    ]
